alias: Enable sleeping
id: enable_sleeping
trigger:
- platform: state
  entity_id: group.all_lights
  to: 'off'
- platform: state
  entity_id: group.downstairs_motion_sensors
  to: 'off'
  for:
    minutes: 20
condition:
- condition: state
  entity_id: group.anyone_home
  state: 'on'
- condition: state
  entity_id: group.all_lights
  state: 'off'
- condition: state
  entity_id: group.downstairs_motion_sensors
  state: 'off'
  for:
    minutes: 20
- condition: time
  after: '22:00:00'
  before: '06:00:00'
action:
- alias: Set asleep
  service: input_boolean.turn_on
  data:
    entity_id: input_boolean.sleeping
