alias: Disable sleeping
id: disable_sleeping
trigger:
- platform: time
  at: '09:00:00'
- platform: state
  entity_id: group.all_motion_sensors
  to: 'on'
condition:
  condition: and
  conditions:
    - condition: time
      after: '08:00:00'
      before: '22:00:00'
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'on'
action:
- alias: Notify
  service: notify.ios_sevenplus
  data:
    message: 'Good morning'
- alias: Set awake
  service: input_boolean.turn_off
  data:
    entity_id: input_boolean.sleeping
