alias: Home for 10 minutes
id: home_10
trigger:
- platform: state
  entity_id: group.anyone_home
  from: 'off'
  to: 'on'
  for:
    minutes: 10
condition:
- condition: state
  entity_id: input_boolean.vacation_mode
  state: 'off'
action:
- alias: Turn on motion
  service: input_boolean.turn_on
  entity_id: input_boolean.home_for_over_10
