alias: Turn off washing machine
initial_state: 'on'
id: turn_off_washing_machine
trigger:
  platform: event
  event_type: ios.notification_action_fired
  event_data:
    actionName: STOP_WASHING_MACHINE
action:
  service: homeassistant.turn_off
  entity_id: switch.washing_machine
