alias: Washing machine off
id: washing_machine_off
trigger:
- platform: numeric_state
  entity_id: sensor.switch_current_watts
  below: 0.8
action:
- alias: Turn on guest mode
  service: input_boolean.turn_off
  entity_id: input_boolean.washing_machine
