stages:
  - test
  - deploy
  - notify

test:
  stage: test
  image: homeassistant/amd64-homeassistant:latest
  script:
    - cp fake_secrets.yaml secrets.yaml
    - cp fake_zones.yaml zones.yaml
    - mkdir /tmp
    - mkdir /images
    - mkdir /config/vacuum
    - mkdir /videos
    - hass --script check_config -c .

