- platform: mqtt
  state_topic: dummy/floorplan/sensor
  name: Floorplan
- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/motion"
  name: "Wallpanel Motion"
  payload_on: '{"value":true}'
  payload_off: '{"value":false}'
  device_class: motion
- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/face"
  name: "Wallpanel Face Detected"
  payload_on: '{"value":true}'
  payload_off: '{"value":false}'
  device_class: motion
- platform: bayesian
  prior: 0.2
  name: 'Sleeping'
  probability_threshold: 0.96
  observations:
      - entity_id: 'input_boolean.home_for_over_10'
        prob_given_true: 0.8
        platform: 'state'
        to_state: 'on'
      - entity_id: 'sun.sun'
        prob_given_true: 0.7
        platform: 'state'
        to_state: 'below_horizon'
      - entity_id: 'group.all_lights_except_nightlight'
        prob_given_true: 0.7
        prob_given_false: 0.4
        platform: 'state'
        to_state: 'off'
      - entity_id: 'input_boolean.motion_last_10'
        prob_given_true: 0.7
        platform: 'state'
        to_state: 'off'
      - entity_id: 'sensor.all_media_players'
        prob_given_true: 0.5
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'off'
      - entity_id: 'binary_sensor.playing_games'
        prob_given_true: 0.3
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'off'
      # - entity_id: 'group.anyone_downstairs'
      #   prob_given_true: 0.4
      #   prob_given_false: 0.1
      #   platform: 'state'
      #   to_state: 'off'
- platform: bayesian
  prior: 0.5
  name: 'Tiia home'
  probability_threshold: 0.7
  observations:
      - entity_id: 'device_tracker.tiiaphone'
        prob_given_true: 0.99
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'sensor.home_occupancy_confidence_tiia'
        prob_given_true: 0.99
        prob_given_false: 0.3
        platform: 'numeric_state'
        above: 33
      - entity_id: 'device_tracker.tiiasiphone'
        prob_given_true: 0.99
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.tiias_iphone'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
- platform: bayesian
  prior: 0.5
  name: 'Luca home'
  probability_threshold: 0.7
  observations:
      - entity_id: 'sensor.home_occupancy_confidence_luca'
        prob_given_true: 0.99
        prob_given_false: 0.3
        platform: 'numeric_state'
        above: 33
      - entity_id: 'device_tracker.sevenplus_router'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.luca_iphone'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
- platform: bayesian
  prior: 0.5
  name: 'Jere home'
  probability_threshold: 0.7
  observations:
#       - entity_id: 'device_tracker.jerephone'
#         prob_given_true: 0.99
#         prob_given_false: 0.3
#         platform: 'state'
#         to_state: 'home'
      - entity_id: 'device_tracker.jeresiphone'
        prob_given_true: 0.5
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.jeres_iphone'
        prob_given_true: 0.8
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'sensor.home_occupancy_confidence_jere'
        prob_given_true: 0.99
        prob_given_false: 0.3
        platform: 'numeric_state'
        above: 32
- platform: bayesian
  prior: 0.5
  name: 'Robin home'
  probability_threshold: 0.7
  observations:
      - entity_id: 'device_tracker.robin_router'
        prob_given_true: 0.99
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
- platform: template
  sensors:
    should_vacuum:
      friendly_name: "Should vacuum"
      value_template: >
       {{ is_state('image_processing.cb_xiaofang2_vacuummodel', 'should_vacuum') and state_attr('image_processing.cb_xiaofang2_vacuummodel', 'should_vacuum') > 55 }}
      icon_template: mdi:robot-vacuum
    people_tf:
      friendly_name: "People detected"
      value_template: >
       {{ is_state('image_processing.tensorflow_people', 'people') }}
      icon_template: mdi:account-multiple
    people_tf_logi:
      friendly_name: "People detected"
      value_template: >
       {{ is_state('image_processing.tensorflow_people_logi', 'people') }}
      icon_template: mdi:account-multiple
    eating:
      friendly_name: "Anyone eating"
      value_template: >
       {{ is_state('image_processing.cb_xiaofang2_latest_eating_model', 'eating') }}
      icon_template: mdi:silverware-fork-knife
    kitchen_lights_on:
      friendly_name: "Kitchen Lights on"
      value_template: >
       {{ is_state('image_processing.cb_xiaofang1_kitchen_lights_model', 'lights_on') }}
      icon_template: mdi:lightbulb-on-outline
    playing_games:
      friendly_name: "Playing games"
      value_template: >
       {{ is_state('sensor.steam_76561197994627749', 'online')  or is_state('sensor.steam_76561198189917609', 'online')}}
      icon_template: mdi:google-controller
    luca_downstairs_wifi:
      friendly_name: "Luca Downstairs Wifi"
      value_template: >
       {{ is_state('device_tracker.sevenplus_router', 'home') and (state_attr('device_tracker.sevenplus_router', 'ap_mac') == '78:8a:20:80:45:b6' or state_attr('device_tracker.sevenplus_router', 'ap_mac') == '18:e8:29:c0:63:87') }}
      icon_template: mdi:wifi
    tiia_downstairs_wifi:
      friendly_name: "Tiia Downstairs Wifi"
      value_template: >
       {{ is_state('device_tracker.tiiasiphone', 'home') and (state_attr('device_tracker.tiiasiphone', 'ap_mac') == '78:8a:20:80:45:b6' or state_attr('device_tracker.tiiasiphone', 'ap_mac') == '18:e8:29:c0:63:87') }}
      icon_template: mdi:wifi
    robin_downstairs_wifi:
      friendly_name: "Robin Downstairs Wifi"
      value_template: >
       {{ is_state('device_tracker.robin_router', 'home') and (state_attr('device_tracker.robin_router', 'ap_mac') == '78:8a:20:80:45:b6' or state_attr('device_tracker.robin_router', 'ap_mac') == '18:e8:29:c0:63:87') }}
      icon_template: mdi:wifi
    luca_upstairs_wifi:
      friendly_name: "Luca Upstairs Wifi"
      value_template: >
       {{ is_state('device_tracker.sevenplus_router', 'home') and state_attr('device_tracker.sevenplus_router', 'ap_mac') == 'fc:ec:da:37:79:6a' }}
      icon_template: mdi:wifi
    tiia_upstairs_wifi:
      friendly_name: "Tiia Upstairs Wifi"
      value_template: >
       {{ is_state('device_tracker.tiiasiphone', 'home') and state_attr('device_tracker.tiiasiphone', 'ap_mac') == 'fc:ec:da:37:79:6a' }}
      icon_template: mdi:wifi
    robin_upstairs_wifi:
      friendly_name: "Robin Upstairs Wifi"
      value_template: >
       {{ is_state('device_tracker.robin_router', 'home') and state_attr('device_tracker.robin_router', 'ap_mac') == 'fc:ec:da:37:79:6a' }}
      icon_template: mdi:wifi
    sonos_speakers:
      friendly_name: "Sonos speakers"
      value_template: >
       {{ is_state('media_player.living_room', 'playing') or is_state('media_player.kitchen', 'playing') or is_state('media_player.bedroom', 'playing') }}
      icon_template: mdi:speaker
    motion_last_10:
      friendly_name: "Motion in the last 10 minutes"
      value_template: >
        {{ not ((as_timestamp(now()) - as_timestamp(states.binary_sensor.living_room_sensor_motion.last_updated) > 600) and is_state('binary_sensor.living_room_sensor_motion','off')) or not ((as_timestamp(now()) - as_timestamp(states.binary_sensor.motion_kitchen_xiaomi.last_updated) > 600) and is_state('binary_sensor.motion_kitchen_xiaomi','off')) or not ((as_timestamp(now()) - as_timestamp(states.binary_sensor.kitchen_sensor_motion.last_updated) > 600) and is_state('binary_sensor.kitchen_sensor_motion','off')) }}
    outdoor_dark:
      friendly_name: "Dark outside"
      value_template: >
        {{ state_attr('binary_sensor.hue_outdoor_motion_sensor_motion_1', 'dark') }}
    outdoor_daylight:
      friendly_name: "Daylight outside"
      value_template: >
        {{ state_attr('binary_sensor.hue_outdoor_motion_sensor_motion_1', 'daylight') }}
    person_outside:
      friendly_name: "Person detected outside"
      value_template: >
        {% set summary = states.image_processing.doods_raspberry.attributes.summary %}
        {% if summary['person'] %}
        True
        {% else %}
        False
        {% endif %}
    car_outside:
      friendly_name: "Person detected outside"
      value_template: >
        {% set summary = states.image_processing.doods_raspberry.attributes.summary %}
        {% if summary['truck'] or summary['car'] %}
        True
        {% else %}
        False
        {% endif %}
    # sonos_speakers:
    #   friendly_name: Sonos speakers
    #   value_template: >
    #     {{ is_state('media_player.living_room', 'playing')
    #     or is_state('media_player.kitchen', 'playing')
    #     or is_state('media_player.bedroom', 'playing') }}
    #   icon_template: mdi:speaker
- platform: ring
- platform: octoprint
  monitored_conditions:
    - Printing
    - Printing Error
