- platform: mqtt
  state_topic: dummy/floorplan/sensor
  name: Floorplan
- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/motion"
  name: "Wallpanel Motion"
  payload_on: '{"value":true}'
  payload_off: '{"value":false}'
  device_class: motion
- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/face"
  name: "Wallpanel Face Detected"
  payload_on: '{"value":true}'
  payload_off: '{"value":false}'
  device_class: motion
- platform: bayesian
  prior: 0.1
  name: 'Sleeping'
  probability_threshold: 0.96
  observations:
      - entity_id: 'input_boolean.home_for_over_10'
        prob_given_true: 0.9
        platform: 'state'
        to_state: 'on'
      - entity_id: 'sun.sun'
        prob_given_true: 0.6
        platform: 'state'
        to_state: 'below_horizon'
      - entity_id: 'group.all_lights_except_nightlight'
        prob_given_true: 0.9
        platform: 'state'
        to_state: 'off'
      - entity_id: 'input_boolean.motion_last_10'
        prob_given_true: 0.7
        platform: 'state'
        to_state: 'off'
      - entity_id: 'sensor.sevenplus_battery_state_2'
        prob_given_true: 0.7
        platform: 'state'
        to_state: 'Charging'
      - entity_id: 'sensor.all_media_players'
        prob_given_true: 0.7
        platform: 'state'
        to_state: 'off'
- platform: bayesian
  prior: 0.5
  name: 'Tiia home'
  probability_threshold: 0.7
  observations:
      - entity_id: 'device_tracker.tiiaphone'
        prob_given_true: 0.99
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'sensor.home_occupancy_confidence_tiia'
        prob_given_true: 0.99
        prob_given_false: 0.3
        platform: 'numeric_state'
        above: 24
      - entity_id: 'device_tracker.tiiasiphone'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.tiias_iphone'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
- platform: bayesian
  prior: 0.5
  name: 'Luca home'
  probability_threshold: 0.7
  observations:
      - entity_id: 'device_tracker.sevenplusbt'
        prob_given_true: 0.99
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'sensor.home_occupancy_confidence_luca'
        prob_given_true: 0.99
        prob_given_false: 0.3
        platform: 'numeric_state'
        above: 24
      - entity_id: 'device_tracker.sevenplus_router'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.sevenplusha'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
- platform: bayesian
  prior: 0.5
  name: 'Jere home'
  probability_threshold: 0.7
  observations:
      - entity_id: 'device_tracker.jerephone'
        prob_given_true: 0.99
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.jeresiphone'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.jeres_iphone'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
- platform: bayesian
  prior: 0.1
  name: 'People detected downstairs'
  probability_threshold: 0.5
  observations:
    - entity_id: 'binary_sensor.people_dafang'
      prob_given_true: 0.8
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'on'
    - entity_id: 'binary_sensor.people_xiaofang2'
      prob_given_true: 0.8
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'on'
    - entity_id: 'binary_sensor.people_tf'
      prob_given_true: 0.8
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'on'
    - entity_id: 'sensor.tensorflow_person_dafang'
      prob_given_true: 0.9
      prob_given_false: 0.5
      platform: 'numeric_state'
      above: '0'
    - entity_id: 'sensor.tensorflow_person_xiaofang1'
      prob_given_true: 0.9
      prob_given_false: 0.5
      platform: 'numeric_state'
      above: '0'
    - entity_id: 'sensor.tensorflow_person_xiaofang2'
      prob_given_true: 0.9
      prob_given_false: 0.5
      platform: 'numeric_state'
      above: '0'
    - entity_id: 'sensor.dafang_people'
      prob_given_true: 0.6
      prob_given_false: 0.3
      platform: 'numeric_state'
      above: '0'
- platform: template
  sensors:
    should_vacuum:
      friendly_name: "Should vacuum"
      value_template: >
       {{ is_state('image_processing.cb_xiaofang2_latest_vacuummodel', 'should_vacuum') and state_attr('image_processing.cb_xiaofang2_latest_vacuummodel', 'should_vacuum') > 60 }}
      icon_template: mdi:robot-vacuum
    people_dafang:
      friendly_name: "People detected living room"
      value_template: >
       {{ is_state('image_processing.cb_dafang_5bd486373f1745fe', 'people') }}
      icon_template: mdi:account-multiple
    people_xiaofang2:
      friendly_name: "People detected living room"
      value_template: >
       {{ is_state('image_processing.cb_xiaofang2_livingroom_presence', 'people') }}
      icon_template: mdi:account-multiple
    people_tf:
      friendly_name: "People Tensorflow"
      value_template: >
       {{ is_state('image_processing.tensorflow_people', 'people') }}
      icon_template: mdi:account-multiple
    eating:
      friendly_name: "Anyone eating"
      value_template: >
       {{ is_state('image_processing.cb_xiaofang2_latest_eatingmodel', 'eating') }}
      icon_template: mdi:silverware-fork-knife
    dining_table_cleaning:
      friendly_name: "Should clean dining table"
      value_template: >
       {{ is_state('image_processing.cb_xiaofang2_dining_table_cleaning', 'should_clean') and state_attr('image_processing.cb_xiaofang2_dining_table_cleaning', 'should_clean') > 55 }}
      icon_template: mdi:spray-bottle
    kitchen_lights_on:
      friendly_name: "Kitchen Lights on"
      value_template: >
       {{ is_state('image_processing.cb_xiaofang1_kitchen_lights_model', 'lights_on') }}
      icon_template: mdi:lightbulb-on-outline
    playing_games:
      friendly_name: "Playing games"
      value_template: >
       {{ is_state('sensor.steam_76561197994627749', 'online')  or is_state('sensor.steam_76561198189917609', 'online')}}
      icon_template: mdi:google-controller
    luca_downstairs_wifi:
      friendly_name: "Luca Downstairs Wifi"
      value_template: >
       {{ is_state('device_tracker.sevenplus_router', 'home') and state_attr('device_tracker.sevenplus_router', 'ap_mac') == '78:8a:20:80:45:b6' }}
      icon_template: mdi:wifi
    tiia_downstairs_wifi:
      friendly_name: "Tiia Downstairs Wifi"
      value_template: >
       {{ is_state('device_tracker.tiiasiphone', 'home') and state_attr('device_tracker.tiiasiphone', 'ap_mac') == '78:8a:20:80:45:b6' }}
      icon_template: mdi:wifi
- platform: ring