- platform: mqtt
  state_topic: dummy/floorplan/sensor
  name: Floorplan
- platform: bayesian
  prior: 0.1
  name: 'Sleeping'
  probability_threshold: 0.96
  observations:
      - entity_id: 'input_boolean.home_for_over_10'
        prob_given_true: 0.9
        platform: 'state'
        to_state: 'on'
      - entity_id: 'sun.sun'
        prob_given_true: 0.6
        platform: 'state'
        to_state: 'below_horizon'
      - entity_id: 'group.all_lights_except_nightlight'
        prob_given_true: 0.9
        platform: 'state'
        to_state: 'off'
      - entity_id: 'input_boolean.motion_last_10'
        prob_given_true: 0.7
        platform: 'state'
        to_state: 'off'
      - entity_id: 'sensor.all_media_players'
        prob_given_true: 0.7
        platform: 'state'
        to_state: 'off'
- platform: bayesian
  prior: 0.1
  name: 'tiia_home'
  probability_threshold: 0.96
  observations:
      - entity_id: 'device_tracker.tiiaphone'
        prob_given_true: 0.9
        prob_given_false: 0.0
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.tiiasiphone'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      