- platform: mqtt
  state_topic: dummy/floorplan/sensor
  name: Floorplan
- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/motion"
  name: "Wallpanel Motion"
  payload_on: '{"value":true}'
  payload_off: '{"value":false}'
  device_class: motion
- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/face"
  name: "Wallpanel Face Detected"
  payload_on: '{"value":true}'
  payload_off: '{"value":false}'
  device_class: motion
- platform: bayesian
  prior: 0.1
  name: 'Sleeping'
  probability_threshold: 0.96
  observations:
      - entity_id: 'input_boolean.home_for_over_10'
        prob_given_true: 0.9
        platform: 'state'
        to_state: 'on'
      - entity_id: 'sun.sun'
        prob_given_true: 0.6
        platform: 'state'
        to_state: 'below_horizon'
      - entity_id: 'group.all_lights_except_nightlight'
        prob_given_true: 0.9
        platform: 'state'
        to_state: 'off'
      - entity_id: 'binary_sensor.motion_last_10'
        prob_given_true: 0.7
        platform: 'state'
        to_state: 'off'
      - entity_id: 'sensor.sevenplus_battery_state_2'
        prob_given_true: 0.7
        platform: 'state'
        to_state: 'Charging'
      - entity_id: 'sensor.all_media_players'
        prob_given_true: 0.7
        platform: 'state'
        to_state: 'off'
- platform: bayesian
  prior: 0.5
  name: 'Tiia home'
  probability_threshold: 0.7
  observations:
      - entity_id: 'device_tracker.tiiaphone'
        prob_given_true: 0.99
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'sensor.home_occupancy_confidence_tiia'
        prob_given_true: 0.99
        prob_given_false: 0.3
        platform: 'numeric_state'
        above: 32
      - entity_id: 'device_tracker.tiiasiphone'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.tiias_iphone'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
- platform: bayesian
  prior: 0.5
  name: 'Luca home'
  probability_threshold: 0.7
  observations:
      - entity_id: 'device_tracker.sevenplusbt'
        prob_given_true: 0.99
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'sensor.home_occupancy_confidence_luca'
        prob_given_true: 0.99
        prob_given_false: 0.3
        platform: 'numeric_state'
        above: 32
      - entity_id: 'device_tracker.sevenplus_router'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.sevenplusha'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
- platform: bayesian
  prior: 0.5
  name: 'Jere home'
  probability_threshold: 0.7
  observations:
      - entity_id: 'device_tracker.jerephone'
        prob_given_true: 0.99
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.jeresiphone'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.jeres_iphone'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
- platform: bayesian
  prior: 0.1
  name: 'People detected downstairs'
  probability_threshold: 0.7
  observations:
    - entity_id: 'binary_sensor.people_xiaofang2_new'
      prob_given_true: 0.8
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'on'
    - entity_id: 'binary_sensor.people_logi'
      prob_given_true: 0.8
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'on'
#     - entity_id: 'binary_sensor.people_tf_logi'
#       prob_given_true: 0.92
#       platform: 'state'
#       to_state: 'on'
#     - entity_id: 'binary_sensor.people_tf'
#       prob_given_true: 0.6
#       prob_given_false: 0.1
#       platform: 'state'
#       to_state: 'on'
    - entity_id: 'sensor.tensorflow_person_xiaofang1'
      prob_given_true: 0.95
      prob_given_false: 0.5
      platform: 'numeric_state'
      above: '0'
    - entity_id: 'sensor.tensorflow_person_xiaofang2'
      prob_given_true: 0.95
      prob_given_false: 0.3
      platform: 'numeric_state'
      above: '0'
    - entity_id: 'sensor.tensorflow_person_logi'
      prob_given_true: 0.8
      prob_given_false: 0.3
      platform: 'numeric_state'
      above: '0'
    - entity_id: 'sensor.livingroom_people'
      prob_given_true: 0.8
      prob_given_false: 0.3
      platform: 'numeric_state'
      above: '0'
- platform: template
  sensors:
    should_vacuum:
      friendly_name: "Should vacuum"
      value_template: >
       {{ is_state('image_processing.cb_xiaofang2_vacuummodel', 'should_vacuum') and state_attr('image_processing.cb_xiaofang2_vacuummodel', 'should_vacuum') > 55 }}
      icon_template: mdi:robot-vacuum
    people_dafang:
      friendly_name: "People detected living room"
      value_template: >
       {{ is_state('image_processing.cb_dafang_5bd486373f1745fe', 'people') }}
      icon_template: mdi:account-multiple
    people_xiaofang2:
      friendly_name: "People detected living room"
      value_template: >
       {{ is_state('image_processing.cb_xiaofang2_livingroom_presence', 'people') }}
      icon_template: mdi:account-multiple
    people_xiaofang2_new:
      friendly_name: "People detected New"
      value_template: >
       {{ is_state('image_processing.cb_xiaofang2_living_room_presence', 'people') }}
      icon_template: mdi:account-multiple
    people_logi:
      friendly_name: "People detected Logi"
      value_template: >
       {{ is_state('image_processing.cb_living_room_presence_model', 'people') }}
      icon_template: mdi:account-multiple
    people_tf:
      friendly_name: "People detected"
      value_template: >
       {{ is_state('image_processing.tensorflow_people', 'people') }}
      icon_template: mdi:account-multiple
    people_tf_logi:
      friendly_name: "People detected"
      value_template: >
       {{ is_state('image_processing.tensorflow_people_logi', 'people') }}
      icon_template: mdi:account-multiple
    people_rekognition_xiaofang2:
      friendly_name: "People Rekognition Xiaofang2"
      value_template: >
       {{ states('image_processing.rekognition_person_xiaofang2')|int > 0 }}
    people_rekognition_logi:
      friendly_name: "People Rekognition Logi"
      value_template: >
       {{ states('image_processing.rekognition_person_living_room')|int > 0 }}
    eating:
      friendly_name: "Anyone eating"
      value_template: >
       {{ is_state('image_processing.cb_xiaofang2_latest_eating_model', 'eating') }}
      icon_template: mdi:silverware-fork-knife
    dining_table_cleaning:
      friendly_name: "Should clean dining table"
      value_template: >
       {{ is_state('image_processing.cb_xiaofang2_dining_table_cleaning', 'should_clean') and state_attr('image_processing.cb_xiaofang2_dining_table_cleaning', 'should_clean') > 55 }}
      icon_template: mdi:spray-bottle
    kitchen_lights_on:
      friendly_name: "Kitchen Lights on"
      value_template: >
       {{ is_state('image_processing.cb_xiaofang1_kitchen_lights_model', 'lights_on') }}
      icon_template: mdi:lightbulb-on-outline
    cats_detected_closet:
      friendly_name: "Cats detected"
      value_template: >
       {{ is_state('image_processing.cb_dafang_cat_model', 'cat') }}
      icon_template: mdi:cat
    playing_games:
      friendly_name: "Playing games"
      value_template: >
       {{ is_state('sensor.steam_76561197994627749', 'online')  or is_state('sensor.steam_76561198189917609', 'online')}}
      icon_template: mdi:google-controller
    luca_downstairs_wifi:
      friendly_name: "Luca Downstairs Wifi"
      value_template: >
       {{ is_state('device_tracker.sevenplus_router', 'home') and state_attr('device_tracker.sevenplus_router', 'ap_mac') == '78:8a:20:80:45:b6' }}
      icon_template: mdi:wifi
    tiia_downstairs_wifi:
      friendly_name: "Tiia Downstairs Wifi"
      value_template: >
       {{ is_state('device_tracker.tiiasiphone', 'home') and state_attr('device_tracker.tiiasiphone', 'ap_mac') == '78:8a:20:80:45:b6' }}
      icon_template: mdi:wifi
    luca_upstairs_wifi:
      friendly_name: "Luca Upstairs Wifi"
      value_template: >
       {{ is_state('device_tracker.sevenplus_router', 'home') and state_attr('device_tracker.sevenplus_router', 'ap_mac') == 'fc:ec:da:37:79:6a' }}
      icon_template: mdi:wifi
    tiia_upstairs_wifi:
      friendly_name: "Tiia Upstairs Wifi"
      value_template: >
       {{ is_state('device_tracker.tiiasiphone', 'home') and state_attr('device_tracker.tiiasiphone', 'ap_mac') == 'fc:ec:da:37:79:6a' }}
      icon_template: mdi:wifi
    sonos_speakers:
      friendly_name: "Sonos speakers"
      value_template: >
       {{ is_state('media_player.living_room', 'playing') or is_state('media_player.kitchen', 'playing') or is_state('media_player.bedroom', 'playing') }}
      icon_template: mdi:speaker
    motion_last_10:
      friendly_name: "Motion in the last 10 minutes"
      value_template: >
        { ((as_timestamp(now()) - as_timestamp(states.binary_sensor.living_motion_room.last_updated) > 600) and is_state('binary_sensor.living_motion_room','off')) and ((as_timestamp(now()) - as_timestamp(states.binary_sensor.motion_kitchen_xiaomi.last_updated) > 600) and is_state('binary_sensor.motion_kitchen_xiaomi','off')) and ((as_timestamp(now()) - as_timestamp(states.binary_sensor.motion_kitchen.last_updated) > 600) and is_state('binary_sensor.motion_kitchen','off')) }}
    # sonos_speakers:
    #   friendly_name: Sonos speakers
    #   value_template: >
    #     {{ is_state('media_player.living_room', 'playing')
    #     or is_state('media_player.kitchen', 'playing')
    #     or is_state('media_player.bedroom', 'playing') }}
    #   icon_template: mdi:speaker
- platform: ring
- platform: hue
- platform: octoprint
  monitored_conditions:
    - Printing
    - Printing Error