- platform: mqtt
  state_topic: dummy/floorplan/sensor
  name: Floorplan
- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/motion"
  name: "Wallpanel Motion"
  payload_on: '{"value":true}'
  payload_off: '{"value":false}'
  device_class: motion
- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/face"
  name: "Wallpanel Face Detected"
  payload_on: '{"value":true}'
  payload_off: '{"value":false}'
  device_class: motion
- platform: bayesian
  prior: 0.1
  name: 'Sleeping'
  probability_threshold: 0.96
  observations:
      - entity_id: 'input_boolean.home_for_over_10'
        prob_given_true: 0.9
        platform: 'state'
        to_state: 'on'
      - entity_id: 'sun.sun'
        prob_given_true: 0.6
        platform: 'state'
        to_state: 'below_horizon'
      - entity_id: 'group.all_lights_except_nightlight'
        prob_given_true: 0.9
        platform: 'state'
        to_state: 'off'
      - entity_id: 'input_boolean.motion_last_10'
        prob_given_true: 0.7
        platform: 'state'
        to_state: 'off'
      - entity_id: 'sensor.all_media_players'
        prob_given_true: 0.7
        platform: 'state'
        to_state: 'off'
- platform: bayesian
  prior: 0.5
  name: 'Tiia home'
  probability_threshold: 0.7
  observations:
      - entity_id: 'device_tracker.tiiaphone'
        prob_given_true: 0.99
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.tiiasiphone'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.tiias_iphone'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
- platform: bayesian
  prior: 0.5
  name: 'Luca home'
  probability_threshold: 0.7
  observations:
      - entity_id: 'device_tracker.sevenplusbt'
        prob_given_true: 0.99
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.sevenplus_router'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.sevenplusha'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
- platform: bayesian
  prior: 0.5
  name: 'Jere home'
  probability_threshold: 0.7
  observations:
      - entity_id: 'device_tracker.jerephone'
        prob_given_true: 0.99
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.jeresiphone'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      - entity_id: 'device_tracker.jeres_iphone'
        prob_given_true: 0.6
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'home'
      
      