# - platform: ffmpeg
#   name: DaFang
#   input: !secret dafang_input
#   extra_arguments: '-pred 1 -q:v 2'
# - platform: ffmpeg
#   name: DaFang mobile
#   input: !secret dafang_input_2
- platform: generic
  name: DaFang
  username: !secret camera_user
  password: !secret camera_pw
  authentication: basic
  stream_source: !secret dafang_stream_url
  still_image_url: !secret dafang_url
  verify_ssl: false
- platform: local_file
  name: Dafang Latest
  file_path: '/images/dafang/latest.jpg'
- platform: local_file
  name: Dafang Snapshot 1
  file_path: '/images/dafang/snapshot1.jpg'
- platform: local_file
  name: Dafang Snapshot 2
  file_path: '/images/dafang/snapshot2.jpg'
- platform: local_file
  name: Dafang Snapshot 3
  file_path: '/images/dafang/snapshot3.jpg'
- platform: local_file
  name: Dafang Snapshot 4
  file_path: '/images/dafang/snapshot4.jpg'
- platform: local_file
  name: Dafang Snapshot 5
  file_path: '/images/dafang/snapshot5.jpg'

# - platform: ffmpeg
#   name: Xiaofang1
#   input: !secret xiaofang1_input
#   extra_arguments: '-pred 1 -q:v 2'
# - platform: ffmpeg
#   name: Xiaofang1 mobile
#   input: !secret dafang_input
- platform: generic
  name: Xiaofang1
  username: !secret camera_user
  password: !secret camera_pw
  authentication: basic
  still_image_url: !secret xiaofang1_url
  stream_source: !secret xiaofang1_stream_url
  verify_ssl: false
- platform: local_file
  name: Xiaofang1 Latest
  file_path: '/images/xiaofang1/latest.jpg'
- platform: local_file
  name: Xiaofang1 Snapshot 1
  file_path: '/images/xiaofang1/snapshot1.jpg'
- platform: local_file
  name: Xiaofang1 Snapshot 2
  file_path: '/images/xiaofang1/snapshot2.jpg'
- platform: local_file
  name: Xiaofang1 Snapshot 3
  file_path: '/images/xiaofang1/snapshot3.jpg'
- platform: local_file
  name: Xiaofang1 Snapshot 4
  file_path: '/images/xiaofang1/snapshot4.jpg'
- platform: local_file
  name: Xiaofang1 Snapshot 5
  file_path: '/images/xiaofang1/snapshot5.jpg'

# - platform: ffmpeg
#   name: Xiaofang2
#   input: !secret xiaofang2_input
#   extra_arguments: '-pred 1 -q:v 2'
- platform: generic
  name: Xiaofang2
  username: !secret camera_user
  password: !secret camera_pw
  authentication: basic
  still_image_url: !secret xiaofang2_url
  stream_source: !secret xiaofang2_stream_url
  verify_ssl: false
# - platform: ffmpeg
#   name: Xiaofang2 mobile
#   input: !secret dafang_input
- platform: local_file
  name: Xiaofang2 Latest
  file_path: '/images/xiaofang2/latest.jpg'
- platform: local_file
  name: Xiaofang2 Snapshot 1
  file_path: '/images/xiaofang2/snapshot1.jpg'
- platform: local_file
  name: Xiaofang2 Snapshot 2
  file_path: '/images/xiaofang2/snapshot2.jpg'
- platform: local_file
  name: Xiaofang2 Snapshot 3
  file_path: '/images/xiaofang2/snapshot3.jpg'
- platform: local_file
  name: Xiaofang2 Snapshot 4
  file_path: '/images/xiaofang2/snapshot4.jpg'
- platform: local_file
  name: Xiaofang2 Snapshot 5
  file_path: '/images/xiaofang2/snapshot5.jpg'

- platform: local_file
  name: Logi Latest
  file_path: '/images/logi/latest.jpg'
- platform: local_file
  name: Logi Snapshot 1
  file_path: '/images/logi/snapshot1.jpg'
- platform: local_file
  name: Logi Snapshot 2
  file_path: '/images/logi/snapshot2.jpg'
- platform: local_file
  name: Logi Snapshot 3
  file_path: '/images/logi/snapshot3.jpg'
- platform: local_file
  name: Logi Snapshot 4
  file_path: '/images/logi/snapshot4.jpg'
- platform: local_file
  name: Logi Snapshot 5
  file_path: '/images/logi/snapshot5.jpg'


- platform: local_file
  name: Tensorflow Xiaofang1
  file_path: '/images/xiaofang1/tensorflow.jpg'
- platform: local_file
  name: Tensorflow Xiaofang2
  file_path: '/images/xiaofang2/tensorflow.jpg'
- platform: local_file
  name: Tensorflow Dafang
  file_path: '/images/dafang/tensorflow.jpg'
- platform: local_file
  name: Tensorflow Logi
  file_path: '/images/logi/tensorflow.jpg'
- platform: local_file
  name: Tensorflow Raspberry
  file_path: '/images/raspberry/tensorflow.jpg'
- platform: local_file
  name: Tensorflow Raspberry Latest
  file_path: '/images/raspberry/tensorflow_latest.jpg'

# - platform: tensorflow
#   camera: camera.xiaofang2_latest
#   processor: image_processing.tensorflow_xiaofang2_latest
#   name: Tensorflow Xiaofang2
#   classifier: ''
# - platform: tensorflow
#   camera: camera.xiaofang1_latest
#   processor: image_processing.tensorflow_xiaofang1_latest
#   name: Tensorflow Xiaofang1
#   classifier: ''
# - platform: tensorflow
#   camera: camera.dafang_latest
#   processor: image_processing.tensorflow_dafang_latest
#   # Optional Parameters
#   name: Tensorflow Dafang
#   classifier: ''
# - platform: sighthound
#   camera: camera.logi_latest
#   processor: image_processing.sighthound_logi_latest
#   # Optional Parameters
#   name: Sighthound Logi
#   classifier: ''

# - platform: ffmpeg
#   name: Raspberry
#   input: !secret raspberry_input
#   extra_arguments: '-pred 1 -q:v 2'
# - platform: mjpeg
#   name: OctoPrint
#   still_image_url: !secret octoprint_still_url
#   mjpeg_url: !secret octoprint_camera
- platform: mjpeg
  name: Raspberry
  still_image_url: !secret raspberry_snapshot
  mjpeg_url: !secret raspberry_input
- platform: generic
  name: Raspberry Generic
  still_image_url: !secret raspberry_snapshot
  stream_source: !secret raspberry_input
- platform: local_file
  name: Raspberry Latest
  file_path: '/images/raspberry/latest.jpg'
- platform: local_file
  name: Raspberry Snapshot 1
  file_path: '/images/raspberry/snapshot1.jpg'
- platform: local_file
  name: Raspberry Snapshot 2
  file_path: '/images/raspberry/snapshot2.jpg'
- platform: local_file
  name: Raspberry Snapshot 3
  file_path: '/images/raspberry/snapshot3.jpg'
- platform: local_file
  name: Raspberry Snapshot 4
  file_path: '/images/raspberry/snapshot4.jpg'
- platform: local_file
  name: Raspberry Snapshot 5
  file_path: '/images/raspberry/snapshot5.jpg'
  
# - platform: generic
#   name: Xiaofang2 Tensorflow
#   still_image_url: >
#     {{ 'https://awesomeplex.duckdns.org:8123'+states.camera.tensorflow_xiaofang2.attributes.entity_picture }}
# - platform: generic
#   name: Xiaofang1 Tensorflow
#   still_image_url: >
#     {{ 'https://awesomeplex.duckdns.org:8123'+states.camera.tensorflow_xiaofang1.attributes.entity_picture }}
# - platform: generic
#   name: Dafang Tensorflow
#   still_image_url: >
#     {{ 'https://awesomeplex.duckdns.org:8123'+states.camera.tensorflow_dafang.attributes.entity_picture }}
# - platform: generic
#   name: Logi Sighthound
#   still_image_url: >
#     {{ 'https://awesomeplex.duckdns.org:8123'+states.camera.sighthound_logi.attributes.entity_picture }}
# - platform: generic
#   name: Vacuum Map
#   still_image_url: 'https://awesomeplex.duckdns.org:8123/local/navmap.png'
#   content_type: image/png
#   framerate: 1
- platform: local_file
  name: Vacuum Map
  file_path: '/images/vacuum_maps/latest.png'
- platform: local_file
  name: Vacuum Map Snapshot 1
  file_path: '/images/vacuum_maps/snapshot1.png'
- platform: local_file
  name: Vacuum Map Snapshot 2
  file_path: '/images/vacuum_maps/snapshot2.png'
- platform: local_file
  name: Vacuum Map Snapshot 3
  file_path: '/images/vacuum_maps/snapshot3.png'
- platform: local_file
  name: Vacuum Map Snapshot 4
  file_path: '/images/vacuum_maps/snapshot4.png'
- platform: local_file
  name: Vacuum Map Snapshot 5
  file_path: '/images/vacuum_maps/snapshot5.png'
- platform: ring
- platform: mjpeg
  name: OctoPrint
  still_image_url: !secret octoprint_still_url
  mjpeg_url: !secret octoprint_camera