homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Helsinki
  customize: !include customize.yaml
  # whitelist_external_dirs:
  #   - '/tmp'
  #   - '/images'
  #   - '/config/vacuum'
  #   - '/videos'
# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes
  extra_html_url:
    - /local/custom_ui/state-card-floorplan.html
    - /local/luca_gps.html
    - /local/tiia_gps.html
lovelace:
  mode: yaml

system_health:

mobile_app:

hacs:
  token: !secret hacs_token
  python_script: true
  theme: true

# custom_updater:
#   card_urls:
#     - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
#     - https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-google-calendar-card/master/custom_updater.json
#   component_urls:
#     - https://raw.githubusercontent.com/keatontaylor/custom_components/master/custom_components.json

# panel_custom: !include panel_custom.yaml

panel_iframe:
  luca:
    title: 'Luca GPS'
    url: '/local/luca_gps.html'
    icon: mdi:human-male
  tiia:
    title: 'Tiia GPS'
    url: '/local/tiia_gps.html'
    icon: mdi:human-female
  networkmap:
    title: 'Zigbee Map'
    url: '/local/community/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # ssl_certificate: /certs/fullchain.pem
  # ssl_key: /certs/privkey.pem
  #ssl_certificate: !secret ssl_certificate
  #ssl_key: !secret ssl_key
  # base_url: !secret base_url
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/

websocket_api:

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

alexa:

cloud:
  alexa:
    filter:
      include_entities:
        - input_boolean.follow_music
        - input_boolean.schedule_cleaning
        - input_boolean.schedule_kitchen_cleaning
        - input_boolean.cleaning_doublepass
        - input_boolean.auto_lights
        - light.paperlight
        - light.yellow_light
        - light.big_light
        - light.kitchen
        - light.office
        - light.hallway_upstairs
        - light.hallway_downstairs
        - light.ball
        - light.color
        - light.living_room
        - light.desk
        - light.kids_room
        - light.bedroom
        - light.shelf
        - light.christmas_tree
        - scene.bedtime
        - scene.movie_mode_arctic
        - scene.relax
        - scene.reading
        - scene.razer
        - fan.xiaomi_miio_device
        - switch.start_vacuum
        - switch.clean_dining_area
        - switch.clean_kitchen
        - switch.clean_livingroom
        - switch.playstation
        - script.vacuum_clean_dining_area
        - script.vacuum_clean_kitchen
        - script.vacuum_clean_livingroom
        - switch.audiobook
        - switch.air_conditioner
        - script.zootopia
        - script.good_doctor
        - script.criminal_minds
        - script.greys_anatomy
        - media_player.lg_webos_smart_tv
        - media_player.living_room_tv
        - media_player.bedroom_tv
        - media_player.speaker
    entity_config:
      switch.clean_kitchen:
        name: Vacuuming the Kitchen
        description: Vacuum the kitchen
      switch.clean_dining_area:
        name: Vacuuming the dining area
        description: Vacuum the dining area
      switch.clean_livingroom:
        name: Vacuuming the living room
        description: Vacuum the living room
      fan.xiaomi_miio_device:
        name: Air purifier
        description: Xiaomi air purifier
      script.zootopia:
        name: Zootopia
        display_categories: switch
      script.good_doctor:
        name: Good Doctor
        display_categories: switch
      script.criminal_minds:
        name: Criminal Minds
        display_categories: switch
      script.greys_anatomy:
        name: Grey's Anatomy
        display_categories: switch
      input_boolean.auto_lights:
        name: Automatic Lights
        display_categories: switch

google:
  client_id: !secret google_cal_id
  client_secret: !secret google_cal_secret
# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - group.all_motion_sensors
      - sensor.motion_livingroom
      - sensor.motion_kitchen
      - group.sensor_kitchen
      - group.sensor_livingroom
      - group.sensor_pi
      - group.sensor_view
      - sensor.fortnite_stats_hotky
      - sensor.fortnite_stats_teacakess
    domains:
      - group

influxdb:
  host: !secret influxdb_ip
  port: 8086
# uncomment if you used a password
#  username: admin
#  password: !secret influxdb_password
  database: homeassistant
  default_measurement: state
  exclude:
    domains:
     - shell_command
     - image_processing
     - calendar
     - camera
     - device_tracker
     - script
    entities:
     - binary_sensor.floorplan
     - media_player.black_sonos_one
     - media_player.white_sonos_one
     - media_player.beam
     - media_player.echo
     - sensor.vacuum_map_walle
     - sensor.vacuum_map_mo
     - sensor.0x00158d00023d8cd6_linkquality
     - sensor.0x00158d00036b7c46_linkquality
     - sensor.0x00158d0003f3f064_linkquality
     - sensor.0x00158d0004144a1b_linkquality
     - sensor.circadian_values
     - sensor.date
     - sensor.date_time
     - sensor.date_time_iso
     - sensor.fortnite_stats_hotky
     - sensor.fortnite_stats_teacakess  
  include:
    entities:
      - device_tracker.sevenplus_router
      - device_tracker.luca_iphone
      - device_tracker.jeresiphone
      - device_tracker.jeres_iphone
      - device_tracker.tiiasiphone
      - device_tracker.tiias_iphone

  

ifttt:
  key: !secret ifttt_key




device_tracker:
#- platform: nmap_tracker
#  hosts: !secret hosts
#  exclude:
#   - !secret raspberry_pi_ip
#  track_new_devices: no
#  consider_home: 800
#  interval_seconds: 10
#  home_interval: 120
#- platform: bluetooth_tracker
#  interval_seconds: 10
#  consider_home: 300
#  track_new_devices: no
- platform: mqtt
  devices:
    sevenplusbt: 'bluetooth_pi/presence/sevenplus'
    tiiaphone: 'bluetooth_pi/presence/tiiaphone'
    jerephone: 'bluetooth_pi/presence/jerephone'
# - platform: unifi_direct
#   host: !secret downstairs_ap_IP
#   username: !secret unifi_user
#   password: !secret unifi_pw
#   track_new_devices: no
# - platform: unifi_direct
#   host: !secret upstairs_ap_IP
#   username: !secret unifi_user
#   password: !secret unifi_pw
#   track_new_devices: no
# - platform: unifi
#   host: !secret unifi_controller_ip
#   username: !secret unifi_user
#   password: !secret unifi_controller_pw
#   verify_ssl: false
#   track_new_devices: false
#   detection_time: 300
#   monitored_conditions:
#     - rssi
#     - signal
#     - ap_mac
#     - name
#     - mac
#     - ip
#     - _last_seen_by_uap
# - platform: icloud
#   username: !secret icloud_user
#   password: !secret icloud_pw

light:
  - platform: group
    name: Livingroom Lights
    entities:
      - light.paperlight
      - light.desk
      - light.big_light
#   - platform: group
#     name: Paperlight
#     entities:
#       - light.paperlight_1
#       - light.paperlight_2
#       - light.paperlight_3
  - platform: group
    name: Bedroom
    entities:
      - light.bedroom_1
      - light.bedroom_2
      - light.bedroom_3
  - platform: group
    name: Kids Room
    entities:
      - light.kids_room_1
      - light.kids_room_2
      - light.kids_room_3
  # - platform: group
  #   name: Hallway Downstairs
  #   entities:room_q
  #     - light.hallway_1
  #     - light.hallway_2
  #     - light.hallway_3
  - platform: mqtt
    name: Dashboard Kitchen
    command_topic: "dashboard/rpi1/set"
    state_topic: "dashboard/rpi1/status"
    brightness_state_topic: 'dashboard/rpi1/brightness'
    brightness_command_topic: 'dashboard/rpi1/brightness/set'
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
  - platform: mqtt
    name: Hallway Downstairs
    schema: json
    command_topic: "zigbee2mqtt/hallway_downstairs/set"
    state_topic: "zigbee2mqtt/hallway_downstairs"
    optimistic: false
    brightness: true
  - platform: mqtt
    name: Paperlight
    schema: json
    command_topic: "zigbee2mqtt/paperlight/set"
    state_topic: "zigbee2mqtt/paperlight"
    optimistic: false
    brightness: true
    color_temp: true
  - platform: mqtt
    name: Entrance
    schema: json
    command_topic: "zigbee2mqtt/entrance/set"
    state_topic: "zigbee2mqtt/entrance"
    availability_topic: "zigbee2mqtt/bridge/state"
    optimistic: false
    brightness: true
    color_temp: true
    xy: true
  - platform: hue
    host: !secret hue_bridge
    allow_hue_groups: false
  - platform: switch
    name: Christmas Tree
    entity_id: switch.christmas_tree
  - platform: switch
    name: Shelf
    entity_id: switch.air_conditioner

circadian_lighting:
  transition: 30
  interval: 1800

# ring:
#   username: !secret ring_user
#   password: !secret ring_pw

logi_circle:
  client_id: !secret logi_client_id
  client_secret: !secret logi_client_secret
  api_key: !secret logi_api_key
  redirect_uri: !secret logi_redirect_uri

tplink:

# Track the sun
sun:

logger:
  default: critical
  logs:
    homeassistant.components: info
    homeassistant.components.http.ban: warning

octoprint:
  host: !secret octoprint_ip
  api_key: !secret octoprint_key
  bed: true
  number_of_tools: 1

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'en-us'

# Additional components
#light:
 #- platform: hue
#   host: !secret hue_bridge

# Sensors
hue:
  bridges:
    - host: !secret hue_bridge

fan:
  - platform: xiaomi_miio
    host: !secret air_purifier_ip
    token: !secret air_purifier_token
    name: Xiaomi Air Purifier

tradfri:
  host: !secret tradfri_ip

climate:
  - platform: netatmo

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_user
  password: !secret netatmo_pw

map:

media_player:
  # - platform: plex
  #   include_non_clients: true
  #   scan_interval: 5
  #   show_all_controls: true
#  - platform: gstreamer
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: webostv
    host: !secret lgtv_ip
    standby_connection: true
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: 78:5D:C8:62:65:D1
  - platform: ps4
    host: !secret ps4waker_ip
    # ps4_ip: !secret ps4_ip
    name: PlayStation 4
    games_filename: '/config/ps4/ps4-games.json'
    # imagemap_json: '/config/ps4/games.json'
    local_store: ''

alexa_media:
  accounts:
    - email: !secret alexa_email
      password: !secret alexa_password
      url: 'amazon.com'

wake_on_lan:

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily

webhook:

media_extractor:
  default_query: best

python_script:

ios:
  push:
      categories:
        - name: Laundry
          identifier: 'laundry'
          actions:
            - identifier: 'STOP_WASHING_MACHINE'
              title: 'Turn off'
              activationMode: 'background'
              destructive: yes
              behavior: 'default'

# browser_mod:

#snips:
mqtt:
  broker: 192.168.92.20
  username: !secret mqtt_user
  password: !secret mqtt_passwd
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

stream:

zigbee2mqtt_networkmap:

homekit: !include homekit.yaml
shell_command:
  rename_snapshots_dafang: 'bash /config/bash_scripts/renameSnapshotsDafang.sh'
  dafang_motion_on: !secret dafang_motion_on
  dafang_motion_off: !secret dafang_motion_off
  rename_snapshots_xiaofang1: 'bash /config/bash_scripts/renameSnapshotsXiaofang1.sh'
  xiaofang1_motion_on: !secret xiaofang1_motion_on
  xiaofang1_motion_off: !secret xiaofang1_motion_off
  reboot_xiaofang1: !secret reboot_xiaofang1
  rename_snapshots_xiaofang2: 'bash /config/bash_scripts/renameSnapshotsXiaofang2.sh'
  xiaofang2_motion_on: !secret xiaofang2_motion_on
  xiaofang2_motion_off: !secret xiaofang2_motion_off
  reboot_xiaofang2: !secret reboot_xiaofang2
  rename_snapshots_raspberry: 'bash /config/bash_scripts/renameSnapshotsRaspberry.sh'
  rename_car: 'bash /config/bash_scripts/renameCar.sh'
  rename_person: 'bash /config/bash_scripts/renamePerson.sh'
  rename_snapshots_backyard: 'bash /config/bash_scripts/renameSnapshotsBackyard.sh'
  export_csv: 'python /config/export_to_csv.py -r {{rssi}} -s {{signal}} -a {{ap}} -l {{location}}'
  export_csv_luca: "python /config/export_to_csv.py -r {{states.device_tracker.sevenplus_router.attributes.rssi}} -s {{states.device_tracker.sevenplus_router.attributes.signal}} -a {% if is_state('binary_sensor.luca_downstairs_wifi','on') %}1{% else %}0{% endif %} -d {% if is_state('input_boolean.luca_downstairs','on') %}1{% else %}0{% endif %}"
  export_csv_tiia: "python /config/export_to_csv.py -r {{states.device_tracker.tiiasiphone.attributes.rssi}} -s {{states.device_tracker.tiiasiphone.attributes.signal}} -a {% if is_state('binary_sensor.tiia_downstairs_wifi','on') %}1{% else %}0{% endif %} -d {% if is_state('input_boolean.tiia_downstairs','on') %}1{% else %}0{% endif %}"
  export_gps_luca: "python /config/export/export_gps.py -t {{states.device_tracker.luca_iphone.attributes.latitude}} -o {{states.device_tracker.luca_iphone.attributes.longitude}} -d '{{states.device_tracker.sevenplusha.attributes.timestamp}}' -p luca"
  export_gps_tiia: "python /config/export/export_gps.py -t {{states.device_tracker.tiias_iphone.attributes.latitude}} -o {{states.device_tracker.tiias_iphone.attributes.longitude}} -d '{{states.device_tracker.tiias_iphone.attributes.timestamp}}' -p tiia"
  plot_luca: "python /config/export/plot.py -p luca"
  plot_tiia: "python /config/export/plot.py -p tiia"
  build_map: 'bash /config/bash_scripts/vacuum_maps.sh'
  rename_vacuum_maps: 'bash /config/bash_scripts/renameVacuumMaps.sh'
  rename_vacuum_maps_walle: 'bash /config/bash_scripts/renameVacuumMapsWalle.sh'
  rename_vacuum_maps_mo: 'bash /config/bash_scripts/renameVacuumMapsMo.sh'
  record_clip: 'bash /config/bash_scripts/recordClip.sh'
  upload_clip: 'bash /config/bash_scripts/uploadClip.sh'
  # install_gmplot: 'pip install gmplot'
  # install_gpxpy: 'pip install gpxpy'
  # install_tensorflow: 'pip3 install tensorflow==1.11.0'
recorder:
  purge_keep_days: 5
  db_url: !secret mysql_db_url
  exclude:
    domains:
     - shell_command
     - image_processing
    entities:
     - media_player.black_sonos_one
     - media_player.white_sonos_one
     - media_player.beam
     - media_player.echo
     - sensor.vacuum_map_walle
     - sensor.vacuum_map_mo

sensor: !include_dir_list sensors
camera: !include cameras.yaml
rest_command: !include rest_commands.yaml
binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
automation: !include_dir_list automations
zone: !include zones.yaml
scene: !include_dir_list scenes
script: !include_dir_merge_named scripts
intent_script: !include_dir_merge_named intent_scripts
notify: !include notify.yaml
switch: !include switches.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml
image_processing: !include image_processing.yaml
timer: !include timer.yaml
