# - platform: sighthound
#   api_key: !secret sighthound_api_key
#   mode: dev
#   state_display: persons
#   scan_interval: 10000
#   source:
#     - entity_id: camera.xiaofang2

##### Classificationbox #####
#   - platform: facebox
#     ip_address: !secret influxdb_ip
#     port: 8081
#     scan_interval: 10000
#     source:
#       - entity_id: camera.dafang_latest
#   - platform: classificationbox
#     ip_address: !secret influxdb_ip
#     port: 8083
#     model_id: 5bd486373f1745fe
#     confidence: 50
#     scan_interval: 10000
#     source:
#       - entity_id: camera.dafang
# - platform: classificationbox
#   ip_address: !secret influxdb_ip
#   port: 8083
#   confidence: 50
#   # model_id: livingroom_presence
#   scan_interval: 10000
#   source:
#     - entity_id: camera.xiaofang2
# - platform: classificationbox
#   ip_address: !secret influxdb_ip
#   port: 8083
#   confidence: 50
#   model_id: living_room_presence
#   scan_interval: 10000
#   source:
#     - entity_id: camera.xiaofang2
# - platform: classificationbox
#   ip_address: !secret influxdb_ip
#   port: 8083
#   confidence: 50
#   model_id: dining_table_cleaning
#   scan_interval: 10000
#   source:
#     - entity_id: camera.xiaofang2
- platform: classificationbox
  ip_address: !secret influxdb_ip
  port: 8083
  confidence: 50
  model_id: eating_model
  scan_interval: 10000
  source:
    - entity_id: camera.xiaofang2_latest
# - platform: classificationbox
#   ip_address: !secret influxdb_ip
#   port: 8083
#   confidence: 50
#   model_id: eating_model
#   scan_interval: 10000
#   source:
#     - entity_id: camera.xiaofang2_latest
- platform: classificationbox
  ip_address: !secret influxdb_ip
  port: 8083
  confidence: 50
  model_id: vacuummodel
  scan_interval: 10000
  source:
    - entity_id: camera.xiaofang2
- platform: classificationbox
  ip_address: !secret influxdb_ip
  port: 8083
  confidence: 50
  model_id: kitchen_lights_model
  scan_interval: 10000
  source:
    - entity_id: camera.xiaofang1
# - platform: classificationbox
#   ip_address: !secret influxdb_ip
#   port: 8083
#   confidence: 50
#   scan_interval: 10000
#   source:
#     - entity_id: camera.xiaofang1_latest

###### Tensorflow #####
- platform: tensorflow
  source:
    - entity_id: camera.raspberry_latest
  model:
    graph: /config/tensorflow/frozen_inference_graph.pb
  file_out: '/images/raspberry/tensorflow_latest.jpg'
  scan_interval: 10000
- platform: tensorflow
  source:
    - entity_id: camera.raspberry
  model:
    graph: /config/tensorflow/frozen_inference_graph.pb
  file_out: '/images/raspberry/tensorflow.jpg'
  scan_interval: 10000
- platform: tensorflow
  source:
    - entity_id: camera.xiaofang2
  model:
    graph: /config/tensorflow/frozen_inference_graph.pb
  file_out: '/images/xiaofang2/tensorflow.jpg'
  scan_interval: 10000
# - platform: tensorflow2
#   source:
#     - entity_id: camera.xiaofang2
#       name: Tensorflow People
#   model:
#     graph: /config/tensorflow/people.pb
#   scan_interval: 10000
# - platform: tensorflow2
#   source:
#     - entity_id: camera.living_room
#       name: Tensorflow People Logi
#   model:
#     graph: /config/tensorflow/people_logi.pb
#   scan_interval: 10000
- platform: tensorflow
  source:
    - entity_id: camera.dafang
  model:
    graph: /config/tensorflow/frozen_inference_graph.pb
  file_out: '/images/dafang/tensorflow.jpg'
  scan_interval: 10000
- platform: tensorflow
  source:
    - entity_id: camera.xiaofang1
  model:
    graph: /config/tensorflow/frozen_inference_graph.pb
  file_out: '/images/xiaofang1/tensorflow.jpg'
  scan_interval: 10000
- platform: tensorflow
  source:
    - entity_id: camera.logi_latest
  model:
    graph: /config/tensorflow/frozen_inference_graph.pb
  file_out: '/images/logi/tensorflow.jpg'
  scan_interval: 10000

##### Rekognition #####
# - platform: amazon_rekognition
#   aws_access_key_id: !secret aws_rekognition_secret_id
#   aws_secret_access_key: !secret aws_rekognition_secret_key
#   region_name: eu-west-1 # optional region, default us-east-1
#   scan_interval: 20000 # optional to limit calls to the API
#   source:
#     - entity_id: camera.xiaofang2
# 
# - platform: amazon_rekognition
#   aws_access_key_id: !secret aws_rekognition_secret_id
#   aws_secret_access_key: !secret aws_rekognition_secret_key
#   region_name: eu-west-1 # optional region, default us-east-1
#   scan_interval: 20000 # optional to limit calls to the API
#   source:
#     - entity_id: camera.dafang
# 
