#Switches
- platform: template
  switches:
    clean_kitchen:
      friendly_name: 'Clean kitchen'
      value_template: "{{ is_state('script.vacuum_clean_kitchen', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.vacuum_clean_kitchen
      turn_off:
        service: script.turn_on
        entity_id: script.vacuum_stop
    clean_dining_area:
      friendly_name: 'Clean dining area'
      value_template: "{{ is_state('script.vacuum_clean_dining_area', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.vacuum_clean_dining_area
      turn_off:
        service: script.turn_on
        entity_id: script.vacuum_stop
    clean_livingroom:
      friendly_name: 'Clean living room'
      value_template: "{{ is_state('script.vacuum_clean_livingroom', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.vacuum_clean_livingroom
      turn_off:
        service: script.turn_on
        entity_id: script.vacuum_stop
    start_vacuum:
      friendly_name: 'Vacuum'
      value_template: "{{ is_state('vacuum.eve.status', 'Cleaning') }}"
      turn_on:
        service: vacuum.start
        entity_id: vacuum.eve
      turn_off:
        service: vacuum.stop
        entity_id: vacuum.eve
    criminal_minds:
      friendly_name: 'Criminal minds'
      value_template: "{{ is_state('media_player.living_room_tv', 'playing') }}"
      turn_on:
        service: rest_command.criminal_minds
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.living_room_tv
    masterchef:
      friendly_name: 'Master chef'
      value_template: "{{ is_state('media_player.living_room_tv', 'playing') }}"
      turn_on:
        service: rest_command.masterchef
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.living_room_tv
    curious_george:
      friendly_name: 'Curious george'
      value_template: "{{ is_state('media_player.living_room_tv', 'playing') }}"
      turn_on:
        service: rest_command.monkey
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.living_room_tv
    audiobook:
      friendly_name: 'Audiobook'
      value_template: "{{ is_state('media_player.speaker', 'playing') }}"
      turn_on:
        service: rest_command.audiobook
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.speaker
    playstation:
      friendly_name: 'Playstation'
      value_template: "{{ is_state('media_player.playstation_4', 'playing') }}"
      turn_on:
        service: script.turn_on_ps4
      turn_off:
        service: script.turn_off_ps4

- platform: tplink
  host: 192.168.92.31
- platform: broadlink
  host: !secret bedroom_switch_ip
  mac: !secret bedroom_switch_mac
  type: sp3
  friendly_name: 'Bedroom Switch'
- platform: broadlink
  host: !secret kitchen_switch_ip
  mac: !secret kitchen_switch_mac
  type: sp3
  friendly_name: 'Kitchen Switch'
- platform: circadian_lighting
  disable_brightness_adjust: true
  sleep_entity: input_boolean.sleeping
  sleep_state: 'on'
#   disable_entity: input_boolean.anyone_downstairs
#   disable_state: 'off'
  lights_ct:
    - light.paperlight
  lights_rgb:
    - light.big_light
    - light.desk
    - light.yellow_light
    - light.ball
