#Switches
- platform: template
  switches:
    clean_kitchen:
      friendly_name: 'Clean kitchen'
      value_template: "{{ is_state('script.vacuum_clean_kitchen', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.vacuum_clean_kitchen
      turn_off:
        service: script.turn_on
        entity_id: script.vacuum_stop
    clean_dining_area:
      friendly_name: 'Clean dining area'
      value_template: "{{ is_state('script.vacuum_clean_dining_area', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.vacuum_clean_dining_area
      turn_off:
        service: script.turn_on
        entity_id: script.vacuum_stop
    clean_livingroom:
      friendly_name: 'Clean living room'
      value_template: "{{ is_state('script.vacuum_clean_livingroom', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.vacuum_clean_livingroom
      turn_off:
        service: script.turn_on
        entity_id: script.vacuum_stop
    start_vacuum:
      friendly_name: 'Vacuum'
      value_template: "{{ is_state('vacuum.eve.status', 'Cleaning') }}"
      turn_on:
        service: vacuum.turn_on
        entity_id: vacuum.eve
      turn_off:
        service: vacuum.turn_off
        entity_id: vacuum.eve
    criminal_minds:
      friendly_name: 'Criminal minds'
      value_template: "{{ is_state('script.criminal_minds', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.criminal_minds
      turn_off:
        service: script.turn_off
        entity_id: script.criminal_minds
    masterchef:
      friendly_name: 'Master chef'
      value_template: "{{ is_state('script.masterchef', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.masterchef
      turn_off:
        service: script.turn_off
        entity_id: script.masterchef

- platform: tplink
  host: 192.168.92.31
