#Switches
- platform: template
  switches:
    clean_kitchen:
      friendly_name: 'Clean kitchen'
      value_template: "{{ is_state('script.vacuum_clean_kitchen_from_hallway', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.vacuum_clean_kitchen_from_hallway
      turn_off:
        service: script.turn_on
        entity_id: script.vacuum_stop
    start_vacuum:
      friendly_name: 'Vacuum'
      value_template: "{{ is_state('vacuum.eve.status', 'Cleaning') }}"
      turn_on:
        service: vacuum.turn_on
        entity_id: vacuum.eve
      turn_off:
        service: vacuum.turn_off
        entity_id: vacuum.eve

- platform: flux
  lights:
    - light.paperlight_1
    - light.paperlight_2
    - light.paperlight_3
  name: Fluxer
  start_time: '7:00'
  stop_time: '23:00'
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 1900
  brightness: 200
  disable_brightness_adjust: false
  mode: mired

#WIP
- platform: rest
  name: 'Motion Sensor Hallway status'
  resource: !secret motion_sensor_hallway_switch
  body_on: '{"on":"true"}'
  body_off: '{"on":"false"}'

- platform: tplink
  host: 192.168.92.245
