alias: Ungroup Player when motion not detected
trigger:
  - platform: state
    entity_id: group.kitchen_motion_sensors #Entry
    to: 'off'
    for:
      minutes: 2
  - platform: state
    entity_id: binary_sensor.motion_hallway_upstairs #Entry
    to: 'off'
    for:
      minutes: 2
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.follow_music
      state: 'on'
action:
  - service: script.sonos_ungroup_motion
    data_template:
      target_player: >
        {% if trigger.entity_id == 'group.kitchen_motion_sensors' %}
          {% set player = 'media_player.kitchen' %}
        {% elif trigger.entity_id == 'binary_sensor.motion_hallway_upstairs' %}
          {% set player = 'media_player.bedroom' %}
        {% endif %}
        {% if player is not none %}
          {{ player }}
        {% else %}
          false
        {% endif %}
