alias: Stop the Audiobook
id: stop_audiobook
trigger:
  platform: state
  entity_id: input_select.audiobook
  to: None
action:
  service: media_player.turn_off
  data:
    entity_id: media_player.speaker
