alias: Big light on at sunset
id: big_light_on_sunset
trigger:
- event: sunset
  offset: -02:00:00
  platform: sun
- platform: state
  entity_id: group.all_devices
  to: 'home'
condition:
- condition: state
  entity_id: group.all_devices
  state: home
- condition: sun
  after: sunset
  after_offset: -02:10:00
action:
- alias: Light on
  service: light.turn_on
  data_template:
    entity_id: light.big_light
    transition: >
        {% set secondsToSunset = as_timestamp(states.sun.sun.attributes.next_setting) - as_timestamp(now()) | int %}
        {% if  secondsToSunset < 7200 -%}
          {% if secondsToSunset > 3600 %}
            {{ secondsToSunset - 2700 | round(0)}}
          {% else %}
            {{ secondsToSunset | round(0) }}
          {%- endif %}
        {% elif secondsToSunset < 0%}
          0
        {% else %}
          0
        {%- endif %}
    brightness_pct: 100
    color_temp: 500
- alias: Notify
  service: notify.facebook
  data:
    message: >
        {% set secondsToSunset = as_timestamp(states.sun.sun.attributes.next_setting) - as_timestamp(now()) | int %}
        {% if  secondsToSunset > 7200 or secondsToSunset < 0%}
          Fading in the livingroom light after sunset
        {% else %}
          Fading in the livingroom light. {{(secondsToSunset/60) | round(0)}} minutes until the sun sets
        {% endif %}
    target:
      - !secret phonenumber_L
