alias: Notify when lights on after 10
id: 'notify_lights_on'
trigger:
- at: '22:00'
  platform: time
condition:
- condition: state
  entity_id: group.all_devices
  state: not_home
- condition: state
  entity_id: group.all_lights
  state: 'on'
action:
- alias: Notify
  service: notify.facebook
  data:
    message: Some lights are still on
    target:
      - !secret phonenumber_L
