alias: Paperlight on at sunset
id: paperlight_on_sunset
trigger:
- platform: sun
  event: sunset
  offset: -01:15:00
- platform: state
  entity_id: group.all_devices
  to: 'home'
condition:
- condition: state
  entity_id: group.all_devices
  state: home
- condition: sun
  after: sunset
  after_offset: -01:30:00
action:
- alias: Light on
  service: light.turn_on
  data_template:
    entity_id: light.paperlight
    transition: >
        {% set secondsToSunset = as_timestamp(states.sun.sun.attributes.next_setting) - as_timestamp(now()) | int %}
        {% if  secondsToSunset < 7200 %}
            {{ secondsToSunset | round(0) }}
        {% elif secondsToSunset < 0%}
          0
        {% else %}
          0
        {%- endif %}
    brightness_pct: 100
    color_temp: 500
- alias: Notify
  service: notify.facebook
  data:
    message: >
        {% set secondsToSunset = as_timestamp(states.sun.sun.attributes.next_setting) - as_timestamp(now()) | int %}
        {% if  secondsToSunset > 7200 or secondsToSunset < 0%}
          Fading in the paper light after sunset
        {% else %}
          Fading in the paper light. {{(secondsToSunset/60) | round(0)}} minutes until the sun sets
        {% endif %}
    target:
      - !secret phonenumber_L
