alias: Vacuum kitchen
id: vacuum_kitchen
trigger:
- platform: time
  at: '14:30'
- platform: state
  entity_id: group.tracked_devices
  from: home
  to: not_home
  for:
    hours: 1
    minutes: 30
    seconds: 0
condition:
- condition: time
  after: '09:00'
  before: '20:00'
  weekday:
  - mon
  - wed
  - fri
- condition: state
  entity_id: input_boolean.schedule_kitchen_cleaning
  state: 'on'
action:
- service: script.turn_on
  entity_id: script.vacuum_clean_kitchen
- service: input_boolean.turn_off
  entity_id: input_boolean.schedule_kitchen_cleaning
- alias: Notify
  service: notify.facebook
  data:
    message: Cleaning the kitchen...
    target:
      - !secret phonenumber_L
