alias: Vacuum double pass
id: vacuum_double_pass
trigger:
  platform: state
  entity_id: sensor.vacuum_status
  from: 'Returning home'
  to: 'Charging'
condition:
- condition: state
  entity_id: input_boolean.cleaning_doublepass
  state: 'on'
- condition: state
  entity_id: group.tracked_devices
  state: not_home
- condition: time
  after: '09:00'
  before: '20:00'
action:
- alias: Notify
  service: notify.facebook
  data:
    message: Vacuum double pass
    target:
      - !secret phonenumber_L
- service: vacuum.turn_on
  entity_id: vacuum.eve
- service: input_boolean.turn_off
  entity_id: input_boolean.cleaning_doublepass
