alias: Schedule kitchen cleaning
id: motion_kitchen
trigger:
- platform: state
  entity_id: sensor.motion_kitchen
  from: 'off'
  to: 'on'
condition:
- condition: state
  entity_id: group.all_devices
  state: home
- condition: time
  after: '15:00'
  before: '19:00'
- condition: state
  entity_id: input_boolean.schedule_kitchen_cleaning
  state: 'off'
action:
- alias: Schedule kitchen cleaning
  service: input_boolean.turn_on
  entity_id: input_boolean.schedule_kitchen_cleaning
