alias: Kitchen lights on when motion
id: motion_kitchen
trigger:
- platform: state
  entity_id: sensor.motion_sensor_kitchen
  from: 'off'
  to: 'on'
condition:
- condition: state
  entity_id: group.all_devices
  state: home
- condition: time
  after: '15:00'
  before: '19:00'
action:
- alias: Schedule kitchen cleaning
  service: input_boolean.turn_on
  entity_id: input_boolean.schedule_kitchen_cleaning
