alias: Scheduled Vacuum
id: schedule_vacuum
trigger:
- platform: time
  at: '12:30'
- platform: state
  entity_id: group.all_devices
  from: home
  to: not_home
  for:
    hours: 0
    minutes: 20
    seconds: 0
condition:
- condition: time
  after: 09:00
  before: '20:00'
  weekday:
  - tue
  - thu
  - sat
  - sun
- condition: state
  entity_id: group.all_devices
  state: not_home
- condition: template
  value_template: '{{ (as_timestamp(now())-as_timestamp(states.sensor.vacuum_status.last_updated))
    > 43200 }}'
action:
- service: notify.ios_sevenplus
  data:
    message: Cleaning triggered
- service: vacuum.turn_on
  entity_id: vacuum.eve
