alias: Vacuum double pass
initial_state: 'on'
id: vacuum_double_pass
trigger:
  platform: state
  entity_id: sensor.vacuum_status
  from: 'Returning home'
  to: 'Charging'
condition:
- condition: state
  entity_id: input_boolean.cleaning_doublepass
  state: 'on'
- condition: time
  after: '09:00'
  before: '20:00'
action:
- service: vacuum.start
  entity_id: vacuum.eve
- service: input_boolean.turn_off
  entity_id: input_boolean.cleaning_doublepass
