alias: Living room lights on when motion
id: motion_livingroom
trigger:
- platform: state
  entity_id: sensor.motion_sensor_hallway
  from: 'off'
  to: 'on'
condition:
- condition: state
  entity_id: light.big_light
  state: 'off'
- condition: state
  entity_id: group.all_devices
  state: home
- condition: numeric_state
  entity_id: sensor.light_sensor_hallway
  below: 8000
action:
- alias: Turn on automation
  service: automation.turn_on
  entity_id: automation.living_room_lights_off_when_no_motion
- alias: Lights on
  service: light.turn_on
  data:
    entity_id: light.big_light
    transition: 3
    brightness_pct: 75
