alias: Kitchen lights on when motion
id: motion_kitchen
trigger:
- platform: state
  entity_id: sensor.motion_kitchen
  to: 'on'
- platform: numeric_state
  entity_id: sensor.kitchen_light_level
  below: 8000
condition:
- condition: state
  entity_id: light.kitchen_light
  state: 'off'
- condition: state
  entity_id: sensor.motion_kitchen
  state: 'on'
- condition: state
  entity_id: group.tracked_devices
  state: home
- condition: numeric_state
  entity_id: sensor.kitchen_light_level
  below: 8000
action:
- alias: Lights on
  service: light.turn_on
  data:
    entity_id: light.kitchen_light
    brightness_pct: 75
- alias: Turn on automation
  service: automation.turn_on
  entity_id: automation.kitchen_lights_off_when_no_motion
