alias: Kitchen lights off when no motion
id: no_motion_kitchen
trigger:
- platform: state
  entity_id: sensor.motion_kitchen
  from: 'on'
  to: 'off'
  for:
    minutes: 3
action:
- alias: Lights off
  service: light.turn_off
  data:
    entity_id: light.kitchen
- alias: Turn off automation
  service: automation.turn_off
  entity_id: automation.kitchen_lights_off_when_no_motion
