alias: Kitchen lights on when motion
id: motion_kitchen
trigger:
- platform: state
  entity_id: group.kitchen_motion_sensors
  to: 'on'
- platform: numeric_state
  entity_id: sensor.kitchen_light_level
  below: 13000
condition:
- condition: state
  entity_id: light.kitchen_light
  state: 'off'
- condition: state
  entity_id: group.kitchen_motion_sensors
  state: 'on'
- condition: state
  entity_id: group.tracked_devices
  state: home
- condition: numeric_state
  entity_id: sensor.kitchen_light_level
  below: 14000
action:
- alias: Lights on
  service: light.turn_on
  data_template:
    entity_id: light.kitchen_light
    brightness_pct: >
      {% if now().hour < 22 %}
        100
      {% else %}
        {% set light_level = states('sensor.kitchen_light_level')%}
        {% if light_level > '10000' %}
          100
        {% elif light_level > '6000' %}
          50
        {% elif light_level < '2000' %}
          10
        {% endif %}
      {% endif %}
- alias: Turn on automation
  service: automation.turn_on
  entity_id: automation.kitchen_lights_off_when_no_motion
