alias: No one downstairs
id: downstairs_off
trigger:
- platform: state
  entity_id: sensor.downstairs_motion_sensors
  from: 'on'
  to: 'off'
  for:
    minutes: 15
- platform: state
  entity_id: sensor.downstairs_media_players
  from: 'on'
  to: 'off'
  for:
    minutes: 5
- platform: state
  entity_id: group.anyone_home
  to: 'off'
- platform: state
  entity_id: sensor.steam_76561198189917609
  to: 'offline'
- platform: state
  entity_id: binary_sensor.people_detected_downstairs
  to: 'off'
- platform: state
  entity_id: group.anyone_downstairs
  to: 'off'
  for:
    minutes: 2
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: group.anyone_downstairs
      state: 'off'
      for:
        minutes: 2
    - condition: state
      entity_id: sensor.downstairs_media_players
      state: 'off'
    - condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: sensor.downstairs_motion_sensors
              state: 'off'
              for:
                minutes: 5
            - condition: state
              entity_id: binary_sensor.people_detected_downstairs
              state: 'off'
        - condition: and
          conditions:
            - condition: state
              entity_id: sensor.downstairs_motion_sensors
              state: 'off'
              for:
                minutes: 20
            - condition: state
              entity_id: binary_sensor.people_detected_downstairs
              state: 'on'
              
        
action:
- alias: Turn off
  service: input_boolean.turn_off
  entity_id: input_boolean.someone_downstairs
