alias: Play Curious George Books
id: curios_george_books
trigger:
  platform: state
  entity_id: input_select.audiobook
  to: Curious George Books
action:
  service: media_player.play_media
  data:
    entity_id: media_player.speaker
    media_content_id: !secret george_books
    media_content_type: audio/mp4
