alias: Dimmer bedroom
initial_state: 'on' 
id: dimmer_bedroom
trigger:
- platform: state
  entity_id: sensor.dimmer_switch
  to: '2_click'
action:
- service: light.turn_on
  data:
    entity_id: light.yellow_light
    brightness_pct: 100