alias: Fade in big light when dark
id: fade_in_big_light
trigger:
- platform: numeric_state
  entity_id: sensor.livingroom_light_level
  below: 8500
- platform: state
  entity_id: group.all_devices
  to: home
condition:
- condition: state
  entity_id: group.tracked_devices
  state: 'home'
- condition: numeric_state
  entity_id: sensor.livingroom_light_level
  below: 8500
- condition: state
  entity_id: light.big_light
  state: 'off'
action:
- alias: Light on
  service: light.turn_on
  data_template:
    entity_id: light.big_light
    transition: 900
    brightness_pct: >
        {% set brightness_sensor = states.ssensor.livingroom_light_level.state | int %}
        {% if  brightness_sensor < 2000 %}
          100
        {% elif brightness_sensor < 4000 %}
          80
        {% elif brightness_sensor < 6000 %}
          60
        {% else %}
          40
        {% endif %}
    color_temp: 500
- alias: Notify
  service: notify.facebook
  data:
    message: Fading in big light because it's dark
    target:
      - !secret phonenumber_L
