alias: Fade in big light when dark
id: fade_in_big_light
trigger:
- platform: numeric_state
  entity_id: sensor.light_sensor_hallway
  below: 8500
- platform: state
  entity_id: group.all_devices
  to: home
condition:
- condition: state
  entity_id: group.all_devices
  state: home
- condition: numeric_state
  entity_id: sensor.light_sensor_hallway
  below: 8500
- condition: time
  after: '09:00'
  before: '17:00'
action:
- alias: Light on
  service: light.turn_on
  data:
    entity_id: light.big_light
    transition: 1800
    brightness_pct: 100
    color_temp: 500
- alias: Notify
  service: notify.ios_sevenplus
  data:
    message: Fading in big light because it's dark
