alias: Kitchen light level changed
initial_state: 'on' 
id: kitchen_light_level_changed
trigger:
- platform: state
  entity_id: sensor.kitchen_light_level
condition:
- condition: state
  entity_id: light.kitchen
  state: 'off'
  for:
    minutes: 1
- condition: state
  entity_id: binary_sensor.kitchen_lights_on
  state: 'off'
  for:
    minutes: 1
- condition: template
  value_template: "{{ states('sensor.kitchen_light_level')|int < (states('input_number.kitchen_true_light_level')|int)+7500 }}"
action:
- service: input_number.set_value
  data_template:
    entity_id: input_number.kitchen_true_light_level
    value: "{{ states.sensor.kitchen_light_level.state }}"
