alias: Lights off when not home
id: lights_off_not_home
trigger:
- entity_id: group.all_devices
  from: home
  platform: state
  to: not_home
<<<<<<< HEAD
- platform: time
  at: '23:59'
=======
>>>>>>> d408653cd1018fa71c1897691ab81d0622da6ee7
condition:
- condition: state
  entity_id: group.all_devices
  state: not_home
action:
- alias: Notify
  service: notify.ios_sevenplus
  data:
    message: Lights off
- alias: All lights off
  data:
    entity_id: group.all_lights
  service: homeassistant.turn_off
