alias: Welcome home
id: welcome_home
trigger:
- platform: state
  entity_id: group.tracked_devices
  to: 'home'
condition:
- condition: numeric_state
  entity_id: sensor.livingroom_light_level
  below: 8500
action:
- alias: Gateway on
  service: light.turn_on
  data:
    entity_id: light.gateway_light_7811dcaf23d2
    brightness_pct: 75
- alias: Light on
  service: light.turn_on
  data_template:
    entity_id: light.hallway
    transition: 5
    brightness_pct: >
        {% set brightness_sensor = states.sensor.livingroom_light_level.state | int %}
        {% if  brightness_sensor < 2000 %}
          100
        {% elif brightness_sensor < 4000 %}
          80
        {% elif brightness_sensor < 6000 %}
          60
        {% else %}
          40
        {% endif %}
    color_temp: 500
- delay: 0:03
- alias: Light off
  service: light.turn_off
  entity_id: light.hallway
- alias: gateway off
  service: light.turn_off
  entity_id: light.gateway_light_7811dcaf23d2
