alias: Xiaomi button double
initial_state: 'on' 
id: xiaomi_button_double
trigger:
- platform: event
  event_type: xiaomi_aqara.click
  event_data:
    entity_id: binary_sensor.switch_158d0001ae6f8c
    click_type: double
action:
- service: light.turn_on
  data:
    entity_id: light.yellow_light
    brightness_pct: 100
- service: scene.turn_on
  data:
    entity_id: scene.relax
