alias: Xiaomi button bedroom
id: xiaomi_button_bedroom
trigger:
- platform: event
  event_type: click
  event_data:
    entity_id: binary_sensor.switch_158d0001ae6f8c
    click_type: single
action:
- service: light.toggle
  data:
    entity_id: light.yellow_light
#    brightness_pct: 100
